name: Build project

on:
    release:
        types: [published]
    workflow_dispatch: 

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Setup flutter SDK
              uses: flutter-actions/setup-flutter@v3
              with:
                  channel: stable
                  version: 3.24.3
            - run: cd ${{github.workspace}}
            - name: Install dependencies
              run: flutter pub get
            - name: build ipa
              run: flutter build ios --release --no-codesign
            - run: mkdir Payload
            - run: mv build/ios/iphoneos/Runner.app Payload
            - run: zip -r -y Payload.zip Payload/Runner.app
            - run: mv Payload.zip release.ipa
            - name: release
              run:
                gh release upload ${{github.event.release.tag_name}} release.ipa
              env:
                GITHUB_TOKEN: ${{github.token}}
              shell: bash

            
